name: NodeJs CI Compilation code 

on:
  pull_request:
    branches:
      - orgtestb2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run checks
      run: npm test  
